services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper
    container_name: zookeeper-1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    hostname: kafka
    container_name: kafka-1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_ID_NEW_MEMBER_JOIN_TIMEOUT: 300000
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  mongodb:
    image: mongo:8.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  news-publisher:
    build:
      context: ./pub
    container_name: news-publisher
    ports:
      - "9000:8080"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - LOG_LEVEL=INFO
    depends_on:
      - kafka

  news-interesting-subscriber:
    build:
      context: ./sub
    container_name: news-interesting-subscriber
    ports:
      - "8001:8080"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
      - MONGO_DB_NAME=news_db
      - MONGO_COLLECTION_NAME=interesting
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_GROUP_ID=interesting-group
      - KAFKA_TOPIC=interesting
      - LOG_LEVEL=INFO
    depends_on:
      - kafka
      - mongodb

  news-not-interesting-subscriber:
    build:
      context: ./sub
    container_name: news-not-interesting-subscriber
    ports:
      - "8002:8080"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
      - MONGO_DB_NAME=news_db
      - MONGO_COLLECTION_NAME=not_interesting
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_GROUP_ID=not-interesting-group
      - KAFKA_TOPIC=not_interesting
      - LOG_LEVEL=INFO
    depends_on:
      - kafka
      - mongodb

volumes:
  mongodb_data: